/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PodcastsIndexRouteImport } from './routes/podcasts.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as PodcastsIdRouteImport } from './routes/podcasts.$id'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'

const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsIndexRoute = PodcastsIndexRouteImport.update({
  id: '/podcasts/',
  path: '/podcasts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const PodcastsIdRoute = PodcastsIdRouteImport.update({
  id: '/podcasts/$id',
  path: '/podcasts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/more': typeof MoreRoute
  '/radio': typeof RadioRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/podcasts/$id': typeof PodcastsIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/podcasts/': typeof PodcastsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/more': typeof MoreRoute
  '/radio': typeof RadioRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/podcasts/$id': typeof PodcastsIdRoute
  '/articles': typeof ArticlesIndexRoute
  '/podcasts': typeof PodcastsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/more': typeof MoreRoute
  '/radio': typeof RadioRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/podcasts/$id': typeof PodcastsIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/podcasts/': typeof PodcastsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/more'
    | '/radio'
    | '/articles/$slug'
    | '/podcasts/$id'
    | '/articles/'
    | '/podcasts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/more'
    | '/radio'
    | '/articles/$slug'
    | '/podcasts/$id'
    | '/articles'
    | '/podcasts'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/more'
    | '/radio'
    | '/articles/$slug'
    | '/podcasts/$id'
    | '/articles/'
    | '/podcasts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  MoreRoute: typeof MoreRoute
  RadioRoute: typeof RadioRoute
  PodcastsIdRoute: typeof PodcastsIdRoute
  PodcastsIndexRoute: typeof PodcastsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/': {
      id: '/podcasts/'
      path: '/podcasts'
      fullPath: '/podcasts/'
      preLoaderRoute: typeof PodcastsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/podcasts/$id': {
      id: '/podcasts/$id'
      path: '/podcasts/$id'
      fullPath: '/podcasts/$id'
      preLoaderRoute: typeof PodcastsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  MoreRoute: MoreRoute,
  RadioRoute: RadioRoute,
  PodcastsIdRoute: PodcastsIdRoute,
  PodcastsIndexRoute: PodcastsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
