/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PodcastsIndexRouteImport } from './routes/podcasts.index'

const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsIndexRoute = PodcastsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PodcastsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/more': typeof MoreRoute
  '/podcasts': typeof PodcastsRouteWithChildren
  '/radio': typeof RadioRoute
  '/podcasts/': typeof PodcastsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/more': typeof MoreRoute
  '/radio': typeof RadioRoute
  '/podcasts': typeof PodcastsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/more': typeof MoreRoute
  '/podcasts': typeof PodcastsRouteWithChildren
  '/radio': typeof RadioRoute
  '/podcasts/': typeof PodcastsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/articles' | '/more' | '/podcasts' | '/radio' | '/podcasts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/articles' | '/more' | '/radio' | '/podcasts'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/more'
    | '/podcasts'
    | '/radio'
    | '/podcasts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRoute
  MoreRoute: typeof MoreRoute
  PodcastsRoute: typeof PodcastsRouteWithChildren
  RadioRoute: typeof RadioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/': {
      id: '/podcasts/'
      path: '/'
      fullPath: '/podcasts/'
      preLoaderRoute: typeof PodcastsIndexRouteImport
      parentRoute: typeof PodcastsRoute
    }
  }
}

interface PodcastsRouteChildren {
  PodcastsIndexRoute: typeof PodcastsIndexRoute
}

const PodcastsRouteChildren: PodcastsRouteChildren = {
  PodcastsIndexRoute: PodcastsIndexRoute,
}

const PodcastsRouteWithChildren = PodcastsRoute._addFileChildren(
  PodcastsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRoute,
  MoreRoute: MoreRoute,
  PodcastsRoute: PodcastsRouteWithChildren,
  RadioRoute: RadioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
